# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Prod_CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make test properties
        shell: bash
        env:
          PROPERTIES: ${{ secrets.PROPERTIES_TEST }}
        run: |
          mkdir -p ./src/test/resources && cd "$_"
          touch ./application.yml
          echo $PROPERTIES > application.yml

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Docker build
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPO: ${{ secrets.DOCKER_REPO }}
        run: |
          docker build --platform arm64 -t $USERNAME/$REPO:${GITHUB_SHA::7}  -t $USERNAME/$REPO:latest . 
          
      - name: Docker push
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPO: ${{ secrets.DOCKER_REPO }}
        run: |
          docker login -u $USERNAME -p $PASSWORD
          docker push $USERNAME/$REPO:${GITHUB_SHA::7}
          docker push $USERNAME/$REPO:latest
